name： 测试

在：
  推送：
    分行：
      - 测试
  拉取请求：
    分行：
      - 测试

职位：
  最鱼的：
    名称：wimdows-avx2
    运行：Ubuntu-20.04
    环境：
      CC：叮叮当当
      CXX：叮叮当当++
    默认值：
      运行：
        工作目录：Rapfi

    步骤：
      - name： 结帐
        用途：动作/checkout@v3

      - name： 构建
        运行： |
rm -rf build && mkdir build && cd build
cmake ..-DCMAKE_BUILD_TYPE=释放 -DUSE_BMI2=关闭 -DUSE_AVX2=开 -DUSE_AVX=开 -DUSE_SSE=开 -DNO_COMMAND_MODULES=开
cmake --build 。-j2 && strip pbrain-rapfi*
MV -v pbrain-rapfi rapfi-windows-avx2
      - name： 上传到 fishtest （freestyle-20）
        如果： ${{ contains（github.event.head_commit.message， 'f20'） }}
        运行： |
COMMIT_TITLE=$（echo “${{github.event.head_commit.message}}” | head -n 1）
curl http://test.pikafish.org/api/add_task -F engine=@build/rapfi-windows-avx2 -F variant=gomoku_freestyle20 -F “task_name=[f20] $COMMIT_TITLE” -F “password=${{secrets.无}}“ -F ”game_time=10“ -F ”inc_time=0.1“ -F ”深度=-1“ -F ”节点=-1“ -F ”elo0=0“ -F ”elo1=5“ -F ”alpha=0.05“ -F ”beta=0.05“ -F ”可见=0”
      - 名称： 上传到 fishtest （freestyle-15）
        if： ${{ contains（github.event.head_commit.message， 'f15'） }}
        运行： |
COMMIT_TITLE=$（echo “${{github.event.head_commit.message}}” | head -n 1）
curl http://test.pikafish.org/api/add_task -F engine=@build/rapfi-windows-avx2 -F variant=gomoku_freestyle15 -F “task_name=[f15] $COMMIT_TITLE” -F “password=${{secrets.无}}“ -F ”game_time=10“ -F ”inc_time=0.1“ -F ”深度=-1“ -F ”节点=-1“ -F ”elo0=0“ -F ”elo1=5“ -F ”alpha=0.05“ -F ”beta=0.05“ -F ”可见=0”
      - 名称：上传到 fishtest （standard-15）
        if： ${{ contains（github.event.head_commit.message， 's15'） }}
        运行： |
COMMIT_TITLE=$（echo “${{github.event.head_commit.message}}” | head -n 1）
curl http://test.pikafish.org/api/add_task -F engine=@build/rapfi-windows-avx2 -F variant=gomoku_standard15 -F “task_name=[s15] $COMMIT_TITLE” -F “password=${{secrets.无}}“ -F ”game_time=10“ -F ”inc_time=0.1“ -F ”深度=-1“ -F ”节点=-1“ -F ”elo0=0“ -F ”elo1=5“ -F ”alpha=0.05“ -F ”beta=0.05“ -F ”可见=0”
      - 名称：上传到 fishtest （renju-15）
        如果： ${{ contains（github.event.head_commit.message， 'r15'） }}
        运行： |
COMMIT_TITLE=$（echo “${{github.event.head_commit.message}}” | head -n 1）
curl http://test.pikafish.org/api/add_task -F engine=@build/rapfi-windows-avx2 -F variant=gomoku_renju15 -F “task_name=[r15] $COMMIT_TITLE” -F “password=${{secrets.无}}“ -F ”game_time=10“ -F ”inc_time=0.1“ -F ”深度=-1“ -F ”节点=-1“ -F ”elo0=0“ -F ”elo1=5“ -F ”alpha=0.05“ -F ”beta=0.05“ -F ”可见=0”
      - name： 上传
        用途：actions/upload-artifact@v3
        与：
          名称： Fishtest
          路径： Rapfi/build/rapfi-windows-avx2
